### ISSUE TITLE
question about top1 top5

### ISSUE THREAD

**Issue by yunsujeon** [vFones/situation-recognition#1]
i have no idea about top1, top5..

i read many paper about ggnn & situation-recognition,

but there are no explanation about top1, top5 ..etc

so i would like to know about this :

1-verb: 0.33, 1-value: 34.73, 1-value-all: 6.36
5-verb: 1.67, 5-value: 73.02, 5-value-all: 17.32
gt-value: 33.24, gt-value-all: 6.29

what this meaning about..? 
to be exact, i want to know about top1 & top5 's difference.

**Comment by vFones** [comment]
Hi, top 1 and top 5 refer to the most accurate and the the top 5 accurate predictions. In other words is the percentage of accuracy o just one element, and on 5 elements. I hope it is more clear now. 
Maybe you can read here:
https://stackoverflow.com/questions/37668902/evaluation-calculate-top-n-accuracy-top-1-and-top-5
