### ISSUE TITLE
about gt value

### ISSUE THREAD

**Issue by yunsujeon** [vFones/situation-recognition#2]
hi Vittorio!

i have one more question about ground truth

As far as i understand..
top1, top5 is predicted verb and that can compare verb, value, value-all with **Ground Truth**

Pictures about i understand and question.
![20210120_111217](https://user-images.githubusercontent.com/38097792/105117780-75ddb300-5b10-11eb-81d6-d2d2789e9c88.jpg)
![20210120_105436](https://user-images.githubusercontent.com/38097792/105116565-59407b80-5b0e-11eb-869f-9f4bf8a68f6d.jpg)

What properties or prediction compare with GT??

**Comment by vFones** [comment]
GT predictions mean that the comparison is made between nouns value. The verbs is not considered in this metric.

**Comment by yunsujeon** [comment]
> GT predictions mean that the comparison is made between nouns value. The verbs is not considered in this metric.

Thank you! I understood.
That 'GT' word make me confused! haha
